### ISSUE TITLE
firefox 56 nightly 选项里显示不全

### ISSUE THREAD

**Issue by GithubUsername3** [esterTion/Youku-HTML5-Player#58]
那几个外链播放器、自动换集、原生html5前的勾选方框不显示，看不出当前处于勾选与否的状态

**Comment by esterTion** [comment]
浏览器在扩展全局样式添加了一个隐藏多选框，意义不明
[extension.css](chrome://browser/content/extension.css)
```css
input[type="checkbox"] {
  display: none;
}
```
暂时等待官方有没有解释，没有的话我之后自己覆盖他的样式
[https://bugzilla.mozilla.org/show_bug.cgi?id=1373221](https://bugzilla.mozilla.org/show_bug.cgi?id=1373221)
